### ISSUE TITLE
change favicon

### ISSUE THREAD

**Issue by docNord** [Ingenjorsarbete-For-Klimatet/gro-gamlestaden#19]
the icon for the page is currently the ifk logo. Should be the GRO logo.

**Comment by strobba** [comment]
Good point! I missed that.

**Comment by docNord** [comment]
@petermikaelsson is looking to get you a vectorized version of the logo which will look better both on the site and as a favicon.

**Comment by strobba** [comment]
Super nice! I spend like 1 min making it transparent, and it's ugly, I know.
